<?php
/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */

function gmaps_block_help($path, $arg) {
	switch ($path) {
		case "admin/help#gmaps_block":
			return '<p>' . t("To add a new GMaps block, use the 'Add GMap' link on the administer blocks page.") . '</p>';
			break;
	  }
}